src/components/Notes/Notes.css, src/components/Outline/Outline.css, src/components/Selection/Selection.css, src/components/Version/Version.css
=> Fix dark mode.

src/components/Notes/Notes.tsx
=> Importing notes.

README.md, package.json, src/App.css, src/App.tsx, src/components/ThemeToggler/ThemeToggler.tsx, src/utils/IframeController.tsx
=> Make GP theme persistent

src/App.css, src/App.tsx, src/components/Banner/Banner.css, src/components/Banner/Banner.tsx, src/components/Resizable/Resizable.css, src/components/Resizable/Resizable.tsx, src/components/Sidebar/Sidebar.css, src/components/Sidebar/Sidebar.tsx, src/components/ThemeToggler/ThemeToggler.css, src/components/ThemeToggler/ThemeToggler.tsx, src/components/Version/Version.tsx, src/components/Version/util.ts, src/index.css, src/utils/metadata.ts
It's now possible to zoom just the Gray Paper by either zooming in the entire document OR clicking within the iframe and zooming the content of the iframe.
It's also possible to change the split between gray paper and the sidebar. Clicking the draggable handle also hides/shows the sidebar.
Resolves #22 
Resolves #17
=> Resize the sidebar and make some elements not zoomable.

src/App.tsx, src/components/Resizable/Resizable.tsx
I experienced non deterministic problems with the app, for example:
- theme switcher does not work
- text selection does not work
I think the reason is `setInterval` that we have in `App` component so I decided to get rid of it.
Additionally I simplified types in a few places.
=> Get rid of setInterval

src/App.tsx, src/utils/metadata.ts, update-archive.sh
=> Load metadata / graypaper externally

src/utils/metadata.ts
=> Revert to local versions on production.

.github/workflows/node.js.yml, biome.jsonc, package.json, src/components/Version/Version.tsx, src/utils/metadata.ts
Creating another PR to trigger netlify deploy preview.
=> (production) Update to 0.3.7

src/components/LightThemeToggle/LightThemeToggle.tsx, src/components/PdfProvider/PdfProvider.tsx, src/components/PdfViewer/PdfViewer.css, src/components/PdfViewer/PdfViewer.tsx
I actually really liked the "gray" theme that can be obtained by inversion of original gray paper colors. This PR introduces the gray them and the toggle button now toggles between all 3 (dark -> gray -> light).
=> Dark -> Gray -> Light theme.

src/components/SelectionProvider/SelectionProvider.tsx
- fixed an issue where selections in firefox would always extend until the end of the page
=> Fixed selections on Firefox

index.html, package-lock.json, package.json, src/App.css, src/components/Banner/Banner.tsx, src/components/PdfProvider/PdfProvider.tsx, src/components/PdfViewer/PdfViewer.css, src/components/PdfViewer/PdfViewer.tsx, src/components/Resizable/Resizable.css, src/components/Resizable/Resizable.tsx, src/components/Sidebar/Sidebar.css, src/components/Sidebar/Sidebar.tsx, src/vite-env.d.ts, vite.config.ts
1. preload `/metadata.json` & topbar images (optimises both mobile & desktop)
2. Move controls to the top when in mobile view
3. Close the sidebar on mobile initially
4. Switch between (almost) fully open sidebar and closed. Increase the handle size on mobile.
5. Add border padding for the sidebar to make the content actually accessible (no way to scroll there)
=> Some small optimisations for mobile

index.html, package-lock.json, package.json, src/App.css, src/components/Banner/Banner.tsx, src/components/PdfProvider/PdfProvider.tsx, src/components/PdfViewer/PdfViewer.css, src/components/PdfViewer/PdfViewer.tsx, src/components/Resizable/Resizable.css, src/components/Resizable/Resizable.tsx, src/components/Sidebar/Sidebar.css, src/components/Sidebar/Sidebar.tsx, src/vite-env.d.ts, vite.config.ts
* Some optimisations for mobile.
* Biome fixes.
* Fix typescript definitions for prefetch stuff.
* Fix typescript definitions for prefetch stuff.
=> [prod] Some small optimisations for mobile (#87)

src/components/NoteManager/NoteManager.css
=> Make the text area resizable

src/components/Selection/Selection.tsx
Added sub-section instead of section as it is more granular and provides better context.
Closes: #101
=> feat: add subsection title to explain prompt

.github/workflows/links-checker.yml, .github/workflows/matrix-bot.yml, tools/links-check/README.md, tools/links-check/bin/links-check.js, tools/links-check/index.ts, tools/links-check/link.ts, tools/links-check/metadata.ts, tools/links-check/package-lock.json, tools/links-check/package.json, tools/links-check/report.ts, tools/links-check/scan.ts, tools/links-check/tsconfig.json, tools/matrix-bot/package-lock.json, tools/matrix-bot/package.json
This PR adds a tool that can be used to scan a codebase in search for graypaper reader links and do the following:
1. If the link is detected we check if it's the latest available version of GP.
2. In case it's not the latest, we propose the link to the latest version (updated link).
3. In case we can't find the synctex blocks in the latest version's synctex data we display extra info that the link is most likely broken (i.e. there was a significant change) - this logic can be improved further, but for now it's pretty simple.
4. We mark links to the old reader as 🦖
<details>
<summary>Example output</summary>
```
⌛ Outdated links 89/97
📜 dist/pvm/index.d.ts
2762: 🦖 https://graypaper.fluffylabs.dev/#WyI0ODY2YjU5YmMwIiwiMjIiLCJBY2tub3dsZWRnZW1lbnRzIixudWxsLFsiPGRpdiBjbGFzcz1cInQgbTAgeDEwIGgyI …
```
=> Code links checker.

src/components/NoteManager/NoteManager.tsx, src/components/NotesProvider/NotesProvider.tsx
Ability to redo what has been undone earlier.
=> Undo + Redo

src/components/NoteManager/Label.tsx, src/components/NoteManager/LabelsFilter.tsx, src/components/NoteManager/Note.tsx, src/components/NoteManager/NoteLabels.tsx, src/components/NoteManager/NoteLink.tsx, src/components/NoteManager/NoteManager.css, src/components/NoteManager/NoteManager.tsx, src/components/NotesProvider/hooks/useLabels.ts
1. Split label-related components into separate files.
2. Implement editable labels.
=> Editable labels

package-lock.json, package.json, src/components/Label/Label.css, src/components/Label/Label.tsx, src/components/NoteManager/NoteManager.css, src/components/NoteManager/NoteManager.tsx, src/components/NoteManager/components/NotesActions.css, src/components/NoteManager/components/NotesActions.tsx, src/components/NoteRenderer/components/HighlightNote/HighlightNote.css, src/components/NoteRenderer/components/HighlightNote/HighlightNote.tsx, src/components/NotesProvider/NotesProvider.tsx, src/components/NotesProvider/consts/remoteSources.ts, src/components/NotesProvider/hooks/useRemoteNotes.ts, src/components/NotesProvider/types/RemoteSource.ts, src/components/NotesProvider/utils/notesImportExport.ts, src/components/NotesProvider/utils/notesLocalStorage.ts, src/components/NotesProvider/utils/remoteSources.ts, src/components/Outline/Outline.css, src/components/PdfProvider/PdfProvider.tsx, src/components/PdfViewer/PdfViewer.tsx, src/components/RemoteSources/RemoteSources.tsx, src/components/RemoteSources/components/RemoteSource.css, src/components/RemoteSources/components/RemoteSource.tsx, src/components/RemoteSources/components/Versions.tsx, src/components/Tabs/Tabs.css, src/components/ZoomControls/ZoomControls.tsx, src/index.css, src/main.tsx, src/utils/renderMathToString.ts
=> Configure external sources

package-lock.json, tools/links-check/index.ts, tools/links-check/package.json
Resolves #150 
I initially tried switching to `tinyglobby`, but the lib just seems to hang when I give it a path that's outside the cwd 🤷‍♂️
=> Update fast-glob and add some timing info.

package-lock.json, package.json, src/App.tsx, src/components/DownloadThemedPdf/DownloadThemedPdf.tsx, src/components/LightThemeToggle/LightThemeToggle.tsx, src/components/PdfProvider/PdfProvider.tsx, src/components/PdfViewer/PdfViewer.css
(#181 )
Currently supports: 
Be patient, when you click button it takes some time before it spits back the pdf
Added:
- dependency jspdf /w good secure score on socket (98)
- button to download pdf (on main screen over change theme button)
Todo:
=> [181] PDF download with current theme support

package.json, src/components/Sidebar/Sidebar.tsx
- ADDED and FIXED - 'Open Search on S button', just like in Rust Docs
Fixes #224
=> ADDED and FIXED - 'Open Search on S button'

package.json, src/components/Sidebar/Sidebar.tsx
This issue #229 was created due to the issue #224 , where the format and lint wanted to be removed by @tomusdrw .
=> Fix issue #229 - 'That is Refactor npm scripts in package.json'

src/main.tsx
Related: https://github.com/FluffyLabs/shared-ui/pull/14
=> Redirect to beta
